header:
  version: 16
  includes:
    - repo: meta-morello
      file: kas/base.yml

defaults:
  repos:
    branch: scarthgap

repos:
  meta-morello-distro:

  meta-morello:
    url: "https://github.com/The-Capable-Hub/meta-morello"
    commit: "9cbefcfa1ea0f269946a9361b29fbda404c52696"
    layers:
      meta-morello:
      meta-morello-toolchain:

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    commit:  "5124ac4a658899158f4a7a2ddf1d2ca931ec7d0e"
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-webserver:

machine: unset

target:
  - morello-image

local_conf_header:
  base: |
    DISTRO = "morello"
